version: '3.8'

services:
  postgres:
    container_name: db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymbuddy
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./backend/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app
    ports:
      - "9900:5432"


  php:
    build: ./backend
    container_name: php-api
    volumes:
      - ./backend:/var/www/html
    expose:
      - 80
    depends_on:
      - postgres
    networks:
      - app

  frontend:
    image: nginx:alpine
    container_name: frontend-static
    volumes:
      - ./frontend/views:/usr/share/nginx/html
    expose:
      - 80
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8080:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
      - frontend
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres: